lane :test do |options|
  
  puts '------------------------------------------------------'
  puts '--- First signature, test existing keystore import ---'
  puts '------------------------------------------------------'

  match_keystore(
  	git_url: "https://github.com/christopherney/fake-keystores",
  	package_name: "com.match-keystore-plugin.test",
    apk_path: "assets/app-release-unsigned.apk",
    match_secret: "A-very-str0ng-password!",
    existing_keystore: "assets/existing-keystore.jks",
  	override_keystore: true,
    keystore_data: "assets/keystore.json"
  )

  puts 'Keystore Path: ' + lane_context[SharedValues::MATCH_KEYSTORE_PATH]
  puts 'Keystore Alias Name: ' + lane_context[SharedValues::MATCH_KEYSTORE_ALIAS_NAME]
  puts 'Signed APK: ' + lane_context[SharedValues::MATCH_KEYSTORE_APK_SIGNED]

  puts '--------------------------------------------------'
  puts '--- Second signature, test local configuration ---'
  puts '--------------------------------------------------'

  match_keystore(
    git_url: "https://github.com/christopherney/fake-keystores",
    package_name: "com.match-keystore-plugin.test",
    apk_path: "assets/app-release-unsigned.apk",
    match_secret: "A-very-str0ng-password!"
  )

  puts 'Keystore Path: ' + lane_context[SharedValues::MATCH_KEYSTORE_PATH]
  puts 'Keystore Alias Name: ' + lane_context[SharedValues::MATCH_KEYSTORE_ALIAS_NAME]
  puts 'Signed APK: ' + lane_context[SharedValues::MATCH_KEYSTORE_APK_SIGNED]

end
